version: '3.8'

services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  pgdata:
