= Проект Task_Manager_Server

Проект Task_Manager_Server - это микросервис для обработки логики планирования и управления задачами.
== Использование

Для запуска приложения и базы данных выполните следующие шаги:

1. Установите Docker и Docker Compose.

2. Запустите контейнеры Docker с помощью команды `docker-compose up`.

3. Установите переменную окружения DB_CONN со значением postgresql://postgres:postgres@localhost:5433/test?sslmode=disable

4. Примените миграции базы данных с помощью утилиты Migrate

## [source,shell]

## migrate -path ./schema -database 'postgres://postgres:123321@localhost:5433/test?sslmode=disable' up

5. Запустите приложение, используя команду `go run cmd/taskmanagerserver/main.go`.

== API

API предоставляет следующие ресурсы:

=== Получение списка дел пользователя

Метод: `GET`
Путь: `/api/todos/:id`

Описание: Получает список дел пользователя по id пользователя.

Ответ:

- Код 200 (OK) со структурой `Todos []TodoJson` - список дел.

=== Создание новой задачи пользователя

Метод: `POST`
Путь: `/api/createtodo`

Описание: Создает новую задачу пользователя

Параметры:

- Тело запроса (тип: `rest.CreateTodoBody`)

Ответ:

- Код 200 (OK) со структурой `"message": "todo created"` - информация об успешном создании.

=== Удаление задачи пользователя

Метод: `DELETE`
Путь: `/api/deletetodo/:id`

Описание: Удаляет выбранную задачу пользователя по id задачи.

Параметры:

Ответ:

- Код 200 (OK) со структурой `"message": "todo deleted"` - информация об успешном удалении.

=== Обновление задачи пользователя

Метод: `PUT`
Путь: `"/api/changetodo"`

Описание: Обнвовляет данные задачи.

Параметры:

- Тело запроса (тип: `rest.ChangeTodoBody`).

Ответ:

- Код 200 (OK) со структурой `"message": "todo changed"` - информация об успешном измении.
